//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeInventoryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        public int Id { get; set; }
        public string Room { get; set; }
        public string Item { get; set; }
        public string Manufacturer { get; set; }
        public string ModelNumber { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> DatePurchased { get; set; }
        public string WherePurchased { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public decimal EstimatedCurrentValue { get; set; }
        public string Notes { get; set; }
    }
}
